---
group-id: "io.quarkiverse.cxf"
artifact-id: "quarkus-cxf-rt-ws-security"
versions:
- "2.0.2"
- "1.7.3"
- "1.6.0"
- "1.5.13"
- "1.4.0"
- "1.3.0"
- "1.2.0"
- "1.1.0"
- "1.0.0"
- "0.14.0"
exclude-versions: []
