name: "Check for newer platform/extension versions"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

defaults:
  run:
    shell: bash
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_updates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REGISTRY_QUARKUS_BOT_PAT }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configure Git author
        run: |
          git config --local user.name "quarkusbot"
          git config --local user.email "quarkusbot@users.noreply.github.com"

      - name: Run Check Updates script
        uses: jbangdev/jbang-action@v0.100.1
        with:
          script: catalog_check_updates@quarkusio
          scriptargs: --working-directory=.
          trust: https://github.com/quarkusio/

      - name: Push changes to main
        run: git push
